import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Experiments with{" "}
          <a href="https://xstate.js.org/docs/about/concepts.html">XState!</a>
        </h1>

        <div className="max-w-xl">
          <p className={styles.description}>
            <code className={styles.code}>
              A finite state machine is a mathematical model of computation that
              describes the behavior of a system that can be in only one state
              at any given time.
            </code>
          </p>
        </div>

        <div className="grid grid-cols-2">
          <Link href="/xstate">
            <a className={styles.card}>
              <h2>XState &rarr;</h2>
              <p>Promise Resolve/Reject helloworld</p>
            </a>
          </Link>

          <Link href="/dog">
            <a className={styles.card}>
              <h2>An Obedient Dog &rarr;</h2>
              <p>Tell the dog what to do!</p>
            </a>
          </Link>

          <Link href="/undoredo">
            <a className={styles.card}>
              <h2>RedoRedoRedo &rarr;</h2>
              <p>trying out undo and redo handling in an xstate project</p>
            </a>
          </Link>

          <Link href="/reddit">
            <a className={styles.card}>
              <h2>Reddit! &rarr;</h2>
              <p>the redux tutorial, but in xstate</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
